### PR TITLE
Disable collecting/sending envoy metrics

### PR DESCRIPTION
**Pull request by AliceProxy**
## Description
Removes the Agents ability to collect and send Envoy metrics. The features in the DCP that were using these metrics have been sunset, so there is no reason to send them anymore. I did not touch the protos around the metrics streaming RPCs just in-case they are being imported elsewhere since we don't want to break clients running on an older version.

CI and testing generally need a lot of improvement IMO, but I wasn't trying to spend that much time on it at the moment. I also attempted to update to go to 1.20.7 but golangci-lint always gets killed without any kind of info when running on a newer go version and I'm not sure what that is all about right now.

#### Documentation
- [ ] I updated the relevant .md documentation.
- [ ] I updated the relevant website documentation.
- [x] This PR does not require documentation updates.

#### Dependencies
- [x] This PR contains new dependencies
- [ ] This PR does not have any change in dependencies.

#### Testing
- [ ] I provided sufficient test coverage for the modified code.
- [x] The existing tests capture the requirements for the modified code.
- [x] The bulk of my code covered by unit tests.
- [x] I executed manual tests to validate my changes and to avoid regressions.
  
##### Testing Strategy
A few words describing your testing strategy, e.g., manual tests, automated tests, extra validations, etc.

## Dependencies, related issues, and other notes
* List change dependencies, if any.
* List related issues, if any.

### CODE REVIEW

**Comment by AliceProxy** [comment]
Ignore the `test` and `unittest` checks. They are just the old names of the jobs so they will never be reported for this PR since I changed them.

**Review by haq204 — APPROVED** [review]

**Comment by knlambert** [comment]
I think we need the approval from the @datawire/cloud . They own this feature.

**Review by joseldmc — COMMENTED** [review]
As far as I know, the envoy metrics feature is behind a feature flag, currently, [this is enabled for our org and Upchieve](https://datawire.slack.com/archives/C0174LWG5UM/p1688048583108799). I know that someone from sales/support (I don't know who tbh) already contact Upchieve to let them know that the feature will be deprecated, so I don't know if we should ask for confirmation before shipping this change. Also, want to confirm, whether this change will impact all the versions or just from now on.

**Review by joseldmc — APPROVED** [review]
Let's ship it, since Alex has all the context and he was the one requesting I think we should be okay. Thanks @AliceProxy

**Review by knlambert — APPROVED** [review]

**Pull request merged**
